### ISSUE TITLE
Check project management LO

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/innersource#20]
> Does the course meet the learning objectives listed in its description?
>> Yes to all but one.

>> Managing projects - without going to the changed file section, it was not immediately clear what actions I need to take to manage projects appropriately.

Brought up by @rkzm in https://github.com/github/services/issues/5632#issuecomment-484447068

**Comment by brianamarie** [comment]
Documenting the claimed objectives as I review this course:

#### After completing this course, you'll be able to:

- [ ] contrast user versus organization owned projects
- [ ] make recommendations about the number of GitHub organizations you should have
- [ ] create discoverable repositories
- [ ] create robust repository READMEs
- [ ] use issue and pull request templates
- [ ] build transparency into repositories
- [ ] measure the success of InnerSource within your organization
- [ ] distribute your InnerSource toolkit

#### You'll be able to answer questions like:

- [ ] What is the difference between InnerSource and open source?
- [ ] How can my organization create repositories to organize work?
- [ ] How should my organization handle bug reports?
- [ ] How should I document my workflows to share with my team members?
- [ ] How do I measure success in my projects?
