### ISSUE TITLE
InnerSource Repository Setup fails to insert Issues

### ISSUE THREAD

**Issue by JenasysDesign** [githubtraining/innersource#33]
## Bug Report

**Current behavior**
Setup of the InnerSource fundamentals seems to be broken.

**Reproduction**
Steps to reproduce the behavior in the course:
1. Go to https://lab.github.com/githubtraining/innersource-fundamentals
2. Click on Install
3. Create new public repository.
4. Click on the "Start Next Step" action button. 
5. Navigates to https://github.com/JenasysDesign/innersource/issues/1 which doesn't exist in the repository created.

**Expected behavior**
https://github.com/JenasysDesign/innersource/issues should be populated. OR
Innersource repository should include instructions on how to address the missing issues.
 
**Possible solution**
Attempted to run https://lab.github.com/install?owner=githubtraining&course=innersource-fundamentals to see if that resolved the issue, but it failed.

**Comment by a-a-ron** [comment]
Hey @JenasysDesign, thank you for opening this issue. I ran through the course and was able to get the course installed and the issue created as expected. I checked the timestamp on when you installed the course and it aligns with some delays and inconsistent experiences that were being addressed at that time. 

I'm not sure if those issues had something to do with your situation but without digging too much into it I'm thinking it may have been related. Could you un-register and try joining the course again to see if the issue persists? If you are still experiencing the same issue I'm happy to look more into it. Thanks!

**Comment by hectorsector** [comment]
👋 @JenasysDesign I'm assuming the problem you ran into had to do with the GitHub downtime suggested by @a-a-ron above ☝️, so I'll go ahead and close this issue. Feel free to reopen if that's not the case and it's still causing trouble.

**Comment by JenasysDesign** [comment]
It's a little unclear how to remove a gitlab course from your profile. 
Is it a case of deleting the course repo at my end?
